= iSAQB Advanced Level curriculum for *FLEX: Flexible Architectures*

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-flex/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-flex/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-flex.svg["Contributors",link="https://github.com/isaqb-org/curriculum-flex/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-flex.svg["Issues",link="https://github.com/isaqb-org/curriculum-flex/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-flex.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-flex/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content

This repository contains the iSAQB Advanced Level curriculum for *FLEX
- Flexible Architectures* in AsciiDoc.

toc::[]

== How to Contribute or Participate
Create an issue, a merge- or pull-request

== How to Build the Curriculum

1. Clone or download - but include the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-flex.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-flex.git --recursive
----
--
2. You can build this repository with gradle via `./gradlew buildDocs`.
3. Look into the file `build.gradle` to see what attributes you may configure. Watch for:
** the `language` attribute, either `DE` (German) or `EN` (English);
** the output formats called `backends` (pdf and/or html5);
** the document version.

== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

[[copyrighted]]
== Licensing and Copyright

include::LICENSE.adoc[]
