=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Strategic Design

1. Die Teilnehmer sollen ein grundlegendes Verständnis für die Umsetzung von Integrationen mithilfe von Strategic Design aus dem Domain Driven Design und den wesentliche Pattern (bspw. Customer/Supplier) anwenden können. Ziel ist, dass die Teilnehmer die Auswirkungen von Beziehungen zwischen Systemen anhand einer Context Map darstellen und SOLL/IST-Vergleiche erstellen können, die als Entscheidungskriterien für Team-Setup und Organisations-Architektur nutzbar sind.
2. Für die Integration von Legacy-Systemen muss definiert werden, wie mit alten Datenmodellen umgegangen wird. Dazu kann der Ansatz des Strategic Designs mit wesentlichen Patterns wie beispielsweise Anti-Corruption Layer genutzt werden.



[[LZ-3-2]]
==== LZ 3-2: Technische Integrations-Strategie wählen

. Die Teilnehmer sollen die Vor- und Nachteile verschiedener Integrationsmechanismen kennen. Dazu zählen Frontend-Integration mit Mash Ups, Integration auf dem Middle Tier und Integration über Datenbanken oder Datenbank-Replikation.
. Die Teilnehmer können abhängig von den Qualitätszielen und dem Wissen des Teams eine geeignete Integration vorschlagen.
. Die Teilnehmer sollen eine Integrationsstrategie wählen, die auf das jeweilige Problem am besten passt. Das kann beispielsweise eine Frontend-Integration, eine Integration über RPC-Mechanismen, mit Message-orientierter Middleware, mit REST oder über die Replikation von Daten sein.
. Teilnehmer verstehen, dass eine Integrationsstrategie darüber entscheidet, ob eine Abhängigkeit
** erst zur Laufzeit entsteht,
** zur Entwicklungszeit entsteht oder
** beim Deployment entsteht.
. Die Teilnehmer sollen die Konsequenzen und Einschränkungen verstehen, die sich aus der Integration von Systemen über verschiedenen Technologien und Integrationsmuster z. B. in Bezug auf Sicherheit, Antwortzeit oder Latenz ergeben.
. Die Teilnehmer sollten verstehen, dass Messaging Kopplung an das
Datenformat oder an eine API bedingt.  REST macht Vorgaben, die diese
Kopplung reduzieren können (Hypermedia, standardisierte API).
. Die Teilnehmer sollten verstehen, dass synchrone Kommunikation, zum
Beispiel durch RPC, zeitliche Kopplung bedingt. Asynchrone
Kommunikation ermöglicht, diese Kopplung aufzuweichen und erlaubt
unter Umständen, dass ein System den Request oder die Berechnung
weiter bearbeiten kann, ohne dass die
asynchron an Backend-Systeme geschickten Anfragen bereits von diesen
beantwortet wurden.
Entkopplung lässt sich
außerdem durch selektives Kommunikation erreichen.
. Die Teilnehmer verstehen, dass bei der Verwendung von Messaging
und der Kommunikation mit anderen Systemen im Vergleich zum Aufruf
lokaler Funktionen Verfügbarkeit und
Antwortzeiten des Systems beeinträchtigt werden können.
. Die Teilnehmer wissen, dass es für Messaging sogenannte
Message-Oriented Middleware gibt, die bestimmte Garantien gibt
und der Entwickler:in viele Aufgaben erleichtert. Nachrichten können optional
persistiert, gefiltert, transformiert etc. werden. Es gibt
verschiedene Messaging-Patterns wie Request/Reply, Publish/Subscribe
oder Broadcast.
. Eine Integration über Daten ermöglicht hohe Autonomie, die allerdings über die Notwendigkeit zur redundanten Datenhaltung und die damit notwendige Synchronisation erkauft wird. Es darf nicht angenommen werden, dass andere Systeme dieselben Schemata nutzen, weil das eine unabhängige Weiterentwicklung der Schemata verhindert. Daher muss für die Integration eine angemessene Transformation vorgesehen werden.
. Die Teilnehmer sollen verschiedene Ansätze für die Frontend-Integration sowie deren Vor- und Nachteile und Anwendbarkeit abhängig von Kontextkriterien benennen können.
. Die Teilnehmer sollen Techniken für die Integration von Services: REST, RPC, Message-orientierte Middleware kennen.
. Die Teilnehmer sollen Datenbank-Replikationsmechanismen mit ETL-Tools oder anderen Ansätzen kennen.
. Die Teilnehmer sollen Messaging Patterns (Request/Reply, Publish/Subscribe etc.) kennen.
. Die Teilnehmer sollen Messaging Systeme (RabbitMQ, Kafka, etc.), Protokolle (AMQP, MQTT, STOMP, etc.) und APIs (JMS) kennen.

[[LZ-3-3]]
==== LZ 3-3: Makroarchitektur erläutern und Kriterien aufstellen können

. Anhand dieser Ansätze sollen die Teilnehmer eine Makroarchitektur entwerfen können, die zumindest Kommunikation und Sicherheit abdeckt.
. Die Teilnehmer können klare Kriterien benennen anhand derer Entwickler selbständig herausfinden, ob eine (Architektur-)Entscheidung ein Mikro- oder eine Makroarchitektur Entscheidung ist resp. ob sie die Entscheidung allein treffen können oder team-externe Stakeholder in den Entscheidungsprozess einbeziehen müssen


[[LZ-3-4]]
==== LZ 3-4: Domain Events statt RPC für die Integration von Bounded Contexts

. Bei einer Event-Driven Architecture (EDA) werden Remote Procedure Calls (RPC) vermieden oder reduziert, indem Domain Events (vgl. DDD Curriculum) publiziert werden. Domain Events beschreiben Zustandsänderungen. Interessierte Systeme können diese Nachrichten verarbeiten (Publish/Subscribe). Dieses Vorgehen hat Auswirkungen darauf, wie der Zustand gespeichert wird. Während bei einer RPC-basierten Integration der Server die Daten speichern muss, liegt diese Verantwortung bei EDA beim Subscriber. Somit entstehen Replikate (dezentrale Datenhaltung). Die Subscriber fungieren dadurch als Cache für den Publisher. Es können weitere Subscriber hinzugefügt werden, ohne den Publisher zu beeinflussen (außer durch Polling). Monitoring der Event-Flüsse ist wichtig.
. Domain Events können via Messaging publiziert werden. Dabei pusht der Publisher die Nachrichten in ein Messaging System. Alternativ können die Nachrichten auch beim Publisher gepollt werden (bspw. Atom/RSS). Beim Einsatz eines Messaging Systems können Subscriber die Nachrichten per Push oder Pull erhalten. Dies hat Auswirkungen auf den Umgang mit Backpressure.
. Die Teilnehmer sollen Herausforderungen bei der Nutzung gemeinsamer Daten kennen.



[[LZ-3-5]]
==== LZ 3-5: Sicherheit

. Die Teilnehmer sollen einen geeigneten Ansatz für das Umsetzen von Sicherheit (Autorisierung/Authentifizierung) in einem verteilten System konzeptionieren können.
. Die Teilnehmer sollen typische verteilte Sicherheitsmechanismen wie OAuth2, OpenID Connect, SAML oder Kerberos kennen und deren Flows erläutern können.

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Strategic Design

1. Participants should have a basic understanding of the
   implementation of integrations using Strategic Design from Domain
   Driven Design and know fundamental patterns.

2. For the integration of legacy systems, it has to be defined how to
   handle old data models. For this purpose, the approach of strategic
   design can be used with essential patterns such as anti-corruption
   layers.


[[LG-3-2]]
==== LG 3-2: Choosing a technical integration strategy

. The participants should know the benefits and drawbacks of different
  integration mechanisms. These include front-end integration with
  Mash Ups, Middle Tier integration, and integration through databases
  or database replication.

. The participants can propose a suitable integration depending on the
  quality goals and the knowledge of the team.

. The participants should choose an integration strategy that best
  suits the particular problem. This can be, for example, front-end
  integration, integration via RPC mechanisms, message-oriented
  middleware, REST, or replication of data.

. Participants should understand the implications and limitations that
  arise from the integration of systems across different technologies
  and integration patterns, relating to, for example, security,
  response time, or latency.

. The participants should understand that messaging implies coupling
  through the data format or an API.  REST contains conventions that
  can reduce this coupling (hypermedia, standardised API).

. The participants should understand that that synchronous
  communication, for example through RPC, implies temporal coupling.
  Asynchronous communication enables loosening this coupling and may
  enable the system to continue to process a request or a
  computation, even though the requests asynchronously sent to
  backend systems have not been answered yet.  Decoupling can also be
  achieved through selective communication.

. With integrating through messaging, systems communicate through the
  asynchronous exchange of messages. The systems are thus decoupled in
  time. Technically, this is achieved by means of indirection via a
  middleware. Messages can optionally be persisted, filtered,
  transformed, etc. There are different messaging patterns like
  Request / Reply, Publish / Subscribe or Broadcast.

. An integration via data enables high autonomy, nevertheless it is
  bought by the necessity for redundant data storage and the necessary
  synchronisation. It must not be assumed that other systems use the
  same schemes, because this prevents an independent development of
  the schemata. Therefore, an adequate transformation has to be
  provided for the integration.

. The participants should be able to name different approaches for
  front-end integration as well as their benefits and drawbacks and
  applicability according to context criteria.

. The participants should know technologies for the integration of
  services: REST, RPC, message-oriented middleware.

. The participants should know database replication mechanisms using
  ETL tools or other approaches

. The participants should know messaging Patterns (Request / Reply,
  Publish / Subscribe, etc.)

. The participants should know messaging systems (RabbitMQ, Kafka
  etc.), protocols (AMQP, MQTT, STOMP etc.) and APIs (JMS).

[[LG-3-3]]
==== LG 3-3: Explain macro architecture und formulate criteria

. Based on these approaches, participants should be able to design a
  macro architecture that covers at least communication and security.

. The participants can name clear criteria developers can use
  independently to determine if an (architecture) decision is a
  decision about micro architecture or macro architecture, if they can
  make that decision on their own or if they need to involve external
  stakeholders in the decision process.

[[LG-3-4]]
==== LG 3-4: Domain events instead of RPC for integrating bounded contexts

. In an event-driven architecture (EDA), RPC is avoided or reduced by
  publishing domain events. Domain events describe state
  changes. Interested systems can process these messages (Publish /
  Subscribe). This procedure affects how the state is stored. While,
  in an RPC-based integration the server has to store the data, with
  EDA this is the responsibility of the subscriber. Thus, replicas
  arise (decentralised data storage). Thereby, the subscribers act as
  a cache for the publisher. Additional subscribers can be added
  without affecting the publisher (except by polling). Monitoring of
  the event flows is important.

. Domain events can be published via messaging. The publisher pushes
  the messages into a messaging system. Alternatively, the messages
  can be polled from the publisher (e.g., Atom / RSS). When using a
  messaging system, subscribers can receive the messages by push or
  pull. This has implications for dealing with backpressure.


. The participants should know challenges of the usage of shared data.

[[LG-3-5]]
==== LG 3-5: Security

. Participants should be able to design a suitable approach for
  implementing security (authorisation / authentication) in a
  distributed system.

. The participants should know typical distributed security mechanisms
  such as OAuth or Kerberos

// end::EN[]


