=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Technische Integrationen

  * Die Teilnehmer sollen eine Integrationsstrategie wählen, die auf das jeweilige Problem am besten passt. Das kann beispielsweise eine Frontend-Integration, eine Integration über RPC-Mechanismen, mit Message-orientierter Middleware, mit REST oder über die Replikation von Daten sein.
  * Die Teilnehmer können abhängig von den Qualitätszielen und dem Wissen des Teams eine geeignete Integration vorschlagen.
  * Die Teilnehmer sollen die Vor- und Nachteile verschiedener Integrationsmechanismen kennen. Dazu zählen Frontend-Integration mit Mash Ups, Integration auf dem Middle Tier und Integration über Datenbanken oder Datenbank-Replikation.
  * Die Teilnehmer sollen die Konsequenzen und Einschränkungen verstehen, die sich aus der Integration von Systemen über verschiedenen Technologien und Integrationsmuster z. B. in Bezug auf Sicherheit, Antwortzeit oder Latenz ergeben.
  * RPC bezeichnet Mechanismen, um Funktionalität in einem anderen Prozess über Rechnergrenzen hinweg synchron aufzurufen. Dadurch entsteht Kopplung in vielerlei Hinsicht (zeitlich, Datenformat, API). Diese Kopplung hat negative Auswirkungen auf Verfügbarkeit und Antwortzeiten des Systems. REST macht Vorgaben, die diese Kopplung reduzieren können (Hypermedia, standardisierte API). Die zeitliche Kopplung bleibt jedoch grundsätzlich bestehen.
  * Bei der Integration mittels Messaging kommunizieren Systeme durch den asynchronen Austausch von Nachrichten. Die Systeme werden somit zeitlich entkoppelt. Technisch wird dies mittels Indirektion über eine Middleware erreicht. Nachrichten können optional persistiert, gefiltert, transformiert etc. werden. Es gibt verschiedene Messaging Patterns wie Request/Reply, Publish/Subscribe oder Broadcast.
  * Eine Integration über Daten ermöglicht hohe Autonomie, die allerdings über die Notwendigkeit zur redundanten Datenhaltung und die damit notwendige Synchronisation erkauft wird. Es darf nicht angenommen werden, dass andere Systeme dieselben Schemata nutzen, weil das eine unabhängige Weiterentwicklung der Schemata verhindert. Daher muss für die Integration eine angemessene Transformation vorgesehen werden.
  * Die Teilnehmer sollen Ansätze für die Front-End-Integration kennen.
  * Die Teilnehmer sollen Techniken für die Integration von Services: REST, RPC, Message-orientierte Middleware kennen.
  * Die Teilnehmer sollen Datenbank-Replikationsmechanismen mit ETL-Tools oder anderen Ansätzen kennen.
  * Die Teilnehmer sollen Messaging Patterns (Request/Reply, Publish/Subscribe etc.) kennen.
  * Die Teilnehmer sollen Messaging Systeme (RabbitMQ, Kafka etc.), Protokolle (AMQP, MQTT, STOMP etc.) und APIs (JMS) kennen.



[[LZ-3-2]]
==== LZ 3-2: Sicherheit

  * Die Teilnehmer sollen einen geeigneten Ansatz für das Umsetzen von Sicherheit (Autorisierung/Authentifizierung) in einem verteilten System konzeptionieren können.
  * Die Teilnehmer sollen typische verteilte Sicherheitsmechanismen wie OAuth oder Kerberos kennen.

[[LZ-3-3]]
==== LZ 3-3: Makroarchitektur

  * Anhand dieser Ansätze sollen die Teilnehmer eine Makroarchitektur entwerfen können, die zumindest Kommunikation und Sicherheit abdeckt.


[[LZ-3-4]]
==== LZ 3-4: Strategic Design

  * Für die Integration von Legacy-Systemen muss definiert werden, wie mit alten Datenmodellen umgegangen wird. Dazu kann der Ansatz des Strategic Designs mit wesentlichen Patterns wie beispielsweise Anti-Corruption Layer genutzt werden.
  * Die Teilnehmer sollen ein grundlegendes Verständnis für die Umsetzung von Integrationen mit Hilfe von Strategic Design aus dem Domain Driven Design und wesentliche Pattern kennen.
  * Bei einer Event-Driven Architecture (EDA) wird RPC vermieden oder reduziert, indem Domain Events publiziert werden. Domain Events beschreiben Zustandsänderungen. Interessierte Systeme können diese Nachrichten verarbeiten (Publish/Subscribe). Dieses Vorgehen hat Auswirkungen darauf, wie der Zustand gespeichert wird. Während bei einer RPC-basierten Integration der Server die Daten speichern muss, liegt diese Verantwortung bei EDA beim Subscriber. Somit entstehen Replikate (dezentrale Datenhaltung). Die Subscriber fungieren dadurch als Cache für den Publisher. Es können weitere Subscriber hinzugefügt werden, ohne den Publisher zu beeinflussen (außer durch Polling). Monitoring der Event-Flüsse ist wichtig.
  * Domain Events können via Messaging publiziert werden. Dabei pusht der Publisher die Nachrichten in ein Messaging System. Alternativ können die Nachrichten auch beim Publisher gepollt werden (bspw. Atom/RSS). Beim Einsatz eines Messaging Systems können Subscriber die Nachrichten per Push oder Pull erhalten. Dies hat Auswirkungen auf den Umgang mit Backpressure.
  * Die Teilnehmer sollen Herausforderungen bei der Nutzung gemeinsamer Daten kennen.

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Integration Technologies
- The participants should choose an integration strategy that best
  suits the particular problem. This can be, for example, front-end
  integration, integration via RPC mechanisms, message-oriented
  middleware, REST, or replication of data.
- The participants can propose a suitable integration depending on the
  quality goals and the knowledge of the team.
- The participants should know the benefits and drawbacks of different
  integration mechanisms. These include front-end integration with
  Mash Ups, Middle Tier integration, and integration through
  databases or database replication.
- Participants should understand the implications and limitations that
  arise from the integration of systems across different technologies
  and integration patterns, relating to, for example, security,
  response time, or latency.
- RPC means mechanisms for synchronously calling functionality in
  another process over computer boundaries. This results in coupling
  in many respects (time, data format, API). This coupling has a
  negative effect on the availability and response times of the
  system. REST makes guidelines that can reduce this coupling
  (Hypermedia, standardised API). However basically, the temporal
  coupling remains.
- With integrating through messaging, systems communicate through the
  asynchronous exchange of messages. The systems are thus decoupled
  in time. Technically, this is achieved by means of indirection via a
  middleware. Messages can optionally be persisted, filtered,
  transformed, etc. There are different messaging patterns like
  Request / Reply, Publish / Subscribe or Broadcast.
- An integration via data enables high autonomy, nevertheless it is
  bought by the necessity for redundant data storage and the
  necessary synchronisation. It must not be assumed that other systems
  use the same schemes, because this prevents an independent
  development of the schemata. Therefore, an adequate transformation
  has to be provided for the integration.
- Participants should know approaches for front-end integration.
- Participants should know Technologies for the integration of
  services: REST, RPC, message-oriented middleware.
- Participants should know Challenges of the usage of shared data.
- Participants should know Database replication mechanisms using ETL
  tools or other approaches.
- Participants should know Messaging Patterns (Request / Reply,
  Publish / Subscribe, etc.).
- Participants should know Messaging systems (RabbitMQ, Kafka etc.),
  protocols (AMQP, MQTT, STOMP etc.) and APIs (JMS).
  

[[LG-3-2]]
==== LG 3-2: Security
- Participants should be able to design a suitable approach for
  implementing security (authorisation / authentication) in a
  distributed system.
- Typical distributed security mechanisms such as OAuth or Kerberos

[[LG-3-3]]
==== LG 3-3: Macro Architecture
- Based on these approaches, participants should be able to design a
  macro architecture that covers at least communication and security.

[[LG-3-4]]
==== LG 3-4: Strategic Design
- For the integration of legacy systems, it has to be defined how to
  handle old data models. For this purpose, the approach of strategic
  design can be used with essential patterns such as anti-corruption
  layers.
- Participants should have a basic understanding of the implementation
  of integrations using Strategic Design from Domain Driven Design and
  know fundamental patterns.
- In an event-driven architecture (EDA), RPC is avoided or reduced by
  publishing domain events. Domain events describe state
  changes. Interested systems can process these messages (Publish /
  Subscribe). This procedure affects how the state is stored. While,
  in an RPC-based integration the server has to store the data, with
  EDA this is the responsibility of the subscriber. Thus, replicas
  arise (decentralised data storage). Thereby, the subscribers act as
  a cache for the publisher. Additional subscribers can be added
  without affecting the publisher (except by polling). Monitoring of
  the event flows is important.
- Domain events can be published via messaging. The publisher pushes
  the messages into a messaging system. Alternatively, the messages
  can be polled from the publisher (e. g., Atom / RSS). When using a
  messaging system, subscribers can receive the messages by push or
  pull. This has implications for dealing with backpressure.
- Challenges of the usage of shared data
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
