=== {learning-goals}

// tag::DE[]
[[LZ-2-1]]
==== LZ 2-1: Zerlegung in Bausteine

.Was sollen die Teilnehmer können?
* Teilnehmer können für eine gegebene Aufgabenstellung eine Zerlegung in einzelne Bausteine entwerfen.
* Die Teilnehmer sollen die Kommunikationsstruktur der Organisation beim Festlegen der Modulgrenzen berücksichtigen (Gesetz von Conway).
* Die Teilnehmer können einen Plan zur Aufteilung eines Deployment-Monolithen in kleine Services aufstellen.

.Was sollen die Teilnehmer verstehen?
* Teilnehmer verstehen, dass jede Art von Bausteinen neben einer griffigen Bezeichnung eine Beschreibung benötigt,
** was Bausteine dieser Art ausmacht,
** wie ein solcher Baustein zur Laufzeit integriert wird,
** wie ein solcher Baustein (im Sinne des Build-Systems) gebaut wird,
** wie ein solcher Baustein deployt wird,
** wie ein solcher Baustein getestet wird,
** wie ein solcher Baustein skaliert wird.
* Unterschiedliche Grade an Vorgaben für die Entwicklung eines Bausteins können sinnvoll sein. Einige Vorgaben sollten besser übergeordnet allgemein für die Integration mit anderen Bausteinen dieser Art gelten. Die übergreifenden Entscheidungen, die alle Systeme beeinflussen, können eine Makro-Architektur bilden - dazu zählen beispielsweise die Kommunikationsprotokolle oder Betriebsstandards. Mikro-Architektur kann die Architektur eines einzelnen Systems sein. Es ist weitgehend unabhängig von anderen Systemen. Zu große Einschränkungen auf Ebene der Makro-Architektur führen dazu, dass die Architektur insgesamt auf weniger Probleme angewendet werden kann.

.Was sollen die Teilnehmer kennen?
* Die Teilnehmer sollen das Gesetz von Conway kennen.


[[LZ-2-2]]
==== LZ 2-2: Modularisierungskonzepte

.Was sollen die Teilnehmer können?
* Die Teilnehmer sollen technische Modularisierungskonzepte projektspezifisch bewerten und auswählen können.
* Die Teilnehmer sollen die Beziehungen zwischen Modulen sowie zwischen Modulen und Sub-domänen veranschaulichen und analysieren können (Context Mapping).
* Die Teilnehmer können ein Konzept erarbeiten, um ein System aus Services aufzubauen.

.Was sollen die Teilnehmer verstehen?
* Modularisierung hilft Ziele wie Parallelisierung der Entwicklung, unabhängiges Deployment/Austauschbarkeit zur Laufzeit, Rebuild/Reuse von Modulen und leichtere Verständlichkeit des Gesamtsystems zu erreichen.
* Daher ist beispielsweise Continuous Delivery und die Automatisierung von Test und Deployment ein wichtiger Einfluss auf die Modularisierung.
* Modularisierung bezeichnet Dekomposition eines Systems in kleinere Teile. Diese Teile nach der Dekomposition wieder zu integrieren, verursacht organisatorische und technische Auf- wände. Diese Aufwände müssen durch die Vorteile, die durch die Modularisierung erreicht werden, mehr als ausgeglichen werden.
* Je nach gewählter Modularisierungstechnologie besteht Kopplung auf unterschiedlichen Ebenen:
** Sourcecode (Modularisierung mit Dateien, Klassen, Packages, Namensräumen etc.)
** Kompilat (Modularisierung mit JARs, Bibliotheken, DLLs etc.)
** Laufzeitumgebung (Betriebssystem, virtuelle Maschine oder Container)
** Netzwerkprotokoll (Verteilung auf verschiedene Prozesse)
* Eine Kopplung auf Ebene des Sourcecodes erfordert sehr enge Kooperation sowie gemeinsames SCM. Eine Kopplung auf Ebene des Kompilats bedeutet, dass die Bausteine in der Regel gemeinsam deployt werden müssen. Nur eine Verteilung auf unterschiedliche Anwendungen/Prozesse ist praktikabel im Hinblick auf ein unabhängiges Deployment.
* Teilnehmer verstehen, dass eine vollständige Isolation zwischen Bausteinen nur durch eine Trennung in allen Phasen (Entwicklung, Deployment und Laufzeit) gewährleistet werden kann. Ist das nicht der Fall, können unerwünschte Abhängigkeiten nicht ausgeschlossen wer- den. Gleichzeitig verstehen die Teilnehmer auch, dass es sinnvoll sein kann, aus Gründen wie effizienter Ressourcennutzung oder Komplexitätsreduktion auf eine vollständige Isolation zu verzichten.
* Teilnehmer verstehen, dass bei der Verteilung auf unterschiedliche Prozesse manche Abhängigkeiten nicht mehr in der Implementierung existieren, sondern erst zur Laufzeit entstehen. Dadurch steigen die Anforderungen an die Überwachung dieser Schnittstellen.
* Microservices sind unabhängige Deployment-Einheiten und damit auch unabhängige Prozesse, die ihre Funktionen über leichtgewichtige Protokolle exponieren, aber auch ein UI ha- ben können. Für die Implementierung jedes einzelnen Microservices können unterschiedliche Technologieentscheidungen getroffen werden.
* Ein Self-Contained System (SCS) stellt ein fachlich eigenständiges System dar. Es beinhaltet üblicherweise UI und Persistenz. Es kann aus mehreren Microservices bestehen. Fachlich deckt ein SCS meist einen Bounded Context ab.

.Was sollen die Teilnehmer kennen?
* Die Teilnehmer sollen verschiedene technische Mechanismen kennen, um
  ein System zur Entwicklungszeit aufzuteilen: Sourcecode-Dateien, JARs,
  OSGi-Bundles, Module der Programmiersprache.
* Die Teilnehmer sollen verschiedene Möglichkeiten kennen, ein System
  zur Laufzeit aufzuteilen: Prozesse, Microservices, Self-Contained
  Systems.
* Die Teilnehmer sollen "The Twelve-Factor App" kennen.

[[LZ-2-3]]
==== LZ 2-3: Modularisierungsstrategien

.Was sollen die Teilnehmer können?
* Die Teilnehmer können die Konsequenzen verschiedener Modularisierungsstrategien bewerten und den mit der Modularisierung verbundenen Aufwand dem zu erwartenden Nutzen gegenüberstellen.
* Die Teilnehmer können die Auswirkungen der Modularisierungsstrategie auf die Autonomie von Bausteinen zur Entwicklungszeit und zur Laufzeit beurteilen.
* Die Teilnehmer können eine geeignete Modularisierung und eine geeignete Granularität der Modularisierung wählen – abhängig von der Organisation und den Qualitätszielen.

.Was sollen die Teilnehmer verstehen?
* Der Modulschnitt kann entlang fachlicher oder technischer Grenzen erfolgen. In den meisten Fällen empfiehlt sich ein fachlicher Schnitt, da sich so fachliche Anforderungen klarer einem Modul zuordnen lassen und somit nicht mehrere Module für die Umsetzung einer fachlichen Anforderung angepasst werden müssen. Dabei kann jedes Modul sein eigenes Domänenmodell im Sinne eines Bounded Context und damit unterschiedliche Sichten auf ein Geschäfts- objekt mit eigenen Daten haben.
* Teilnehmer verstehen, dass zur Erreichung von höherer Autonomie der Entwicklungsteams ein Komponentenschnitt besser entlang fachlicher Grenzen anstatt entlang technischer Grenzen erfolgt.
* Transaktionale Konsistenz lässt sich über Prozessgrenzen hinweg nur über zusätzliche Mechanismen erreichen. Wird ein System in mehrere Prozesse aufgeteilt, so stellt die Modulgrenze daher häufig auch die Grenze für transaktionale Konsistenz dar. Daher muss ein DDD-Aggregat in einem Modul verwaltet werden.
* Teilnehmer verstehen, welche Modularisierungskonzepte nicht nur für Transaktions-, sondern auch für Batch- und Datenfluss-orientierte Systeme genutzt werden können.

.Was sollen die Teilnehmer kennen?
* Die Teilnehmer kennen die Modularisierungsstrategien "Bounded
  Context", "Customer Journey" und "Information Hiding" <<parnas>>.
* Die Teilnehmer sollen folgende Begriffe aus dem Domain-Driven Design kennen: Aggregate Root, Context Mapping, Bounded Contexts und Beziehungen dazwischen (z. B. Anti-Corruption Layer).


// end::DE[]

// tag::EN[]
[[LG-2-1]]
==== LG 2-1: Decomposing into building blocks

.What shall participants be capable of?

* Participants can design a decomposition into individual blocks for a
  given problem.
* The participants should consider the organisation's communication
  structure when setting the module boundaries (Conway's law).
* The participants can draw up a plan to divide a deployment monolith
  into small services.

.What should participants understand?

* Participants understand that each type of building blocks requires a handy label, as well as a description,
** what makes up this kind of building block
** how such a building block is integrated at runtime
** how such a building block is built (in the sense of the build system)
** how such a building block is deployed
** how such a building block is tested
** how such a building block is scaled
* Different levels of specifications can be useful for the development
  of a module. Some specifications should better be superior valid for
  the integration with other building blocks of this type, in
  general. The overarching decisions that affect all systems can
  form a macro architecture, including, for example, communications
  protocols or operating standards. Micro architecture can be the
  architecture of a single system. It is largely independent of other
  systems. Excessive limitations at the macro architecture level will
  lead to an overall architecture that can be applied to fewer
  problems

.What should participants know?

* The participants should know Conway’s law.

[[LG-2-2]]
==== LG 2-2: Modularisation concepts

.What shall participants be capable of?

* The participants should be able to evaluate and select technical
  modularisation concepts in a project-specific manner.
* The participants should be able to illustrate and analyse the
  relationships between modules as well as between modules and
  subdomains (context mapping).
* Participants can develop a concept to build a system of services.

.What should participants understand?

* Modularisation helps to achieve goals such as parallelization of
  development, independent deployment / interchangeability at runtime,
  rebuild / reuse of modules and easier understanding of the overall
  system.
* Therefore, techniques like continuous delivery and the automation of
  test and deployment are important influences on the modularisation.
* Modularisation means the decomposition of a system into smaller
  parts. Re-integrating these parts after the decomposition causes
  organisational and technical efforts. These efforts have to be
  exceeded by the advantages achieved by the modularisation.
* Depending on the chosen modularisation technology, there is coupling
  on different levels:
** Sourcecode (modularisation with files, classes, packages,
   namespaces etc.)
** Built target (modularisation with JARs, libraries, DLLs, etc.)
** Runtime environment (operating system, virtual machine or
   container)
** Network protocol (distribution to different processes)
* A coupling at the source code level requires very close cooperation
  as well as common SCM. A coupling at the level of the built target
  means that the building blocks must usually be deployed
  together. Only a distribution to different applications / processes
  is feasible with regard to independent deployment.
* Participants understand that a complete isolation between building
  blocks can only be ensured by a separation in all phases
  (development, deployment and runtime). If this is not the case,
  undesirable dependencies cannot be excluded. At the same time, the
  participants also understand that it can be useful to forego
  complete isolation for reasons such as efficient resource usage or
  complexity reduction.
* Participants understand that, when distributing to different
  processes, some dependencies no longer exist in the implementation,
  but rather arise at runtime. This increases the requirements for
  monitoring these interfaces.
* Microservices are independent deployment units and therefore
  independent processes that expose their functions through
  lightweight protocols, but may also have a UI. Different technology
  decisions can be made for the implementation of each individual
  microservice.
* A Self-Contained System (SCS) is a functionally independent
  system. It usually includes UI and persistence. It may consist of
  several Microservices. Usually a SCS covers a functional bounded
  context.

.What should participants know?
* The participants should know various technical modularisation
  options: e.g., source code files, libraries, frameworks, plugins,
  applications, processes, Microservices, SCS.
* The participants should know various technical modularisation
  options: e.g., source files, libraries, frameworks, plugins,
  applications, processes, microservices, self-contained systems
* The participants should know "The Twelve-Factor App". 

[[LG-2-3]]
==== LG 2-3: Modularisation strategies

.What shall participants be capable of?

* Participants can evaluate the consequences of different
  modularisation strategies and compare the efforts of the
  modularisation with the expected benefits.
* Participants can assess the impact of the modularisation strategy
  on the autonomy of building blocks at development time and at run
  time.
* The participants can choose a suitable modularisation as well as a
  suitable granularity of the modularisation - depending on the
  organisation and the quality goals.

.What should participants understand?

* Participants understand that an integration strategy decides whether
  a dependency 
** emerges at runtime
** emerges during development time, or
** emerges at the deployment.
* The module division can be done along functional or technical
  boundaries. In most cases, a functional division is recommended,
  because in this case functional requirements can be assigned more
  clearly to a concrete module, and therefore it is not necessary to
  adapt several modules for the implementation of a single functional
  requirement. Thereby, each module can have its own domain model in
  the sense of a bounded context and thus different views on a
  business object with its own data.
* Participants understand that in order to achieve higher autonomy of
  the development teams, it is better to divide a component along
  functional boundaries rather than along technical boundaries.
* Transactional consistency through
  process boundaries can only be achieved via additional
  mechanisms. So, if a system is divided into several processes, the
  module boundary often also represents the limit for transactional
  consistency. Therefore, a DDD aggregate must be managed in one
  module.
* Participants understand which modularisation concepts can be used
  not only for transactional but also for batch- and
  data-flow-oriented systems.

.What should participants know?
* The participants know the modularisation strategies "bounded
  context", "customer journey", and "information hiding" <<parnas>>.
* The participants should know the following terms from the
  domain-driven design: Aggregate Root, Context Mapping, Bounded
  Contexts and relationships between them (e.g., Anti-Corruption
  Layer).


// end::EN[]





· 




