=== {learning-goals}

// tag::DE[]

[[LZ-2-1]]
==== LZ 2-1: Ziele von Modularisierung

* Architekten verstehen, dass Flexibilität im Kontext dieses Curriculums die Fähigkeit bezeichnet, das System an sich ändernde Anforderungen anzupassen.

* Architekturen verstehen die Rolle des Geheimnisprinzips beim Erreichen von Flexibilität, insbesondere dem Verstecken von Entscheidungen, die schwierig zu treffen oder später schwer zu ändern sind.

* Architekt:innen können Modularisierung benutzen, um konzeptuelle Bausteine auf (technische) Module abzubilden.

* Architekt:innen kennen den Einfluss, den Anforderungen wie unabhängige Deployments, Parallelisierung von Arbeit und Ersetzbarkeit von Technologien auf Modularisierung haben.

[[LZ-2-2]]
==== LZ 2-2: Kopplung

* Architekt:innen verstehen, dass das Ziel von Modularisierung ist, die Kopplung zwischen Modulen zu reduzieren.

* Architekt:innen verstehen mögliche Ursachen von enger Kopplung zwischen Modulen, wie falsch gesetzte Modulgrenzen, schlecht entworfene APIs und übermäßig eingeschränkte Kommunikation zwischen Modulen.

* Architekt:innen können eine Modularisierung bottom-up entwerfen, die Kopplung niedrig hält.

* Architekt:innen können Kopplung reduzieren, indem sie die Kohäsion innerhalb von Modulen steigern.

[[LZ-2-3]]
==== LZ 2-3: Modularisierung und die Organisation

* Architekt:innen können analysieren, wie sich Entscheidungen zu Modulgrenzen auf Komplexität, Koordinationsaufwand für Änderungen sowie Entwicklungs- und Wartungskosten auswirken.

* Architekt:innen verstehen die Rolle von Conway's Law bei der Einschränkung von Modularisierung.

* Architekt:innen verstehen, dass Software-Schnittstellen Kommunikation zwischen Menschen implizieren.

* Architekt:innen verstehen, dass, damit eine externe Schnittstelle für viele Abnehmer:innen nützlich ist, ein Prozess benötigt wird, der Änderungen verwaltet.

* Architekt:inne verstehen die Möglichkeit, die Organisation so zu verändern, dass sie zur Modularisierung passt (Inverse-Conway-Manöver).

* Architekt:innen verstehen die Notwendigkeit, ein System in grobgranulare Bausteine zu zerlegen, bevor Module existieren und können eine solche Zerlegung für ein System top-down entsprechend bekannten Anforderungen entwerfen.

* Architekt:innen können eine angemessene Visualisierung einer Systemzerlegung anfertigen.

* Architekt:innen kennen verschiedene Techniken für grobgranulare Systemzerlegung und ihre Tradeoffs.

* Architekt:innen können organisatorische und technische Kosten für die Integration eines modularen Systems identifizieren.

[[LZ-2-4]]
==== LZ 2-4: Modulmechanismen

* Architekt:innen verstehen Programmiersprachen-Mechanismen, die mit Modularisierung zu tun haben, wie Klassen und Interfaces in objektorientieren Sprachen, Namespace-Mechanismen und ML-artige Modulsprachen.

* Architekt:innen verstehen die Rolle von opaken Schnittstellen bei der Durchsetzung von loser Kopplung.

* Architekt:innen kennen Schnittstellensprachen und ihre Unterschiede wie Java/C#-Interfaces, Java-Packages, .NET-Namespaces und ML-artige Modulsignaturen, und können sie ausnutzen, um lose Kopplung durchzusetzen.

* Architekt:innen kennen nicht-linguistische (nicht in die Programmiersprache eingebaute) Architektur-Management-Ansätze zur Durchsetzung von Modularisierung, wie Tests zu schreiben oder externe Werkzeuge zu benutzen, die auf dem Modul-Abhängigkeitsgraph operieren.

[[LZ-2-5]]
==== LZ 2-5: Dokumentation von Modularisierung

* Architekt:innen verstehen, dass Architekturdokumentation und Modularisierungsimplementierung zueinander passen müssen.

* Architekt:innen können die Prinzipien und Regel der Modularisierungsstrategie dokumentieren.

* Architekt:innen wissen, dass Architekturdokumentation aus entsprechenden Modularisierungsmechanismen generiert werden kann.

// end::DE[]

// tag::EN[]

[[LG-2-1]]
==== LG 2-1: Goals of modularization

* Architects understand that flexibility in the context of this curriculum means the ability to adapt the system to changing requirements.

* Architects understand the role of information hiding to achieve flexibility, specifically the hiding of decisions that are difficult to make or may change later.

* Architects can use modularization to map conceptual building blocks to (technical) modules.

* Architects know the impact on modularization of requirements such as independent deployment, parallelization of work, and replaceability of technologies.

[[LG-2-2]]
==== LG 2-2: Coupling

* Architects understand that the goal of modularization is to reduce coupling between modules.

* Architects understand possible causes of tight coupling between modules, such as misplaced module boundaries, ill-designed APIs, and over-constrained communication between modules.

* Architects understand the special role of mutable state in tight coupling.

* Architects can design a modularization in a bottom-up fashion that will keep coupling low.

* Architects can decrease coupling by increasing cohesion within modules.

[[LG-2-3]]
==== LG 2-3: Modularization and the organization

* Architects can analyze how module boundary choices affect complexity, coordination effort for changes, and development and maintenance costs.

* Architects understand the role of Conway's law in constraining modularization.

* Architects understand that software interfaces imply communication between humans.

* Architects understand that, for an external interface to remain useful to many different clients, a process is required that governs changes.

* Architects understand the possibility of changing the organization to match the modularization (Inverse-Conway-Maneuver).

* Architects understand the need to decompose a system into coarse-grained building blocks before modules exist, and can draft a such a decomposition for a system top-down according to known requirements.

* Architects can produce an appropriate visualization of the system decomposition.

* Architects know different techniques for coarse-grain system decomposition and their tradeoffs.

* Architects can identify organizational and technical costs for integrating a modular system.

[[LG-2-4]]
==== LG 2-4: Module mechanisms

* Architects understand programming-language mechanisms that relate to modularization such as classes and interfaces in object-oriented languages, namespace mechanisms, and ML-style module languages.

* Architects understand the role of opaque interfaces in enforcing loose coupling.

* Architects know interface languages and their differences such as Java/C# interfaces, Java packages, .NET namespaces, and ML-style module signatures, and can leverage them to enforce loose coupling.

* Architects know non-linguistic (not built into the programming language) architecture-management approaches to enforcing modularization such as creating tests and using external tools that operate on the module dependency graph.

* Architects understand the relationship between module mechanisms and deployment strategies.

[[LG-2-5]]
==== LG 2-5: Modularization documentation

* Architects understand that architecture documentation and modularization implementation must be aligned.

* Architects can document the principles and rules of the modularization strategy.

* Architects know that architecture documentation can be generated from appropriate modularization mechanisms.

// end::EN[]
