// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Das Modul {curriculum-name} zeigt, wie Architekt:innen dafür sorgen können, dass Software-Systeme leicht geändert und erweitert werden können.
Im Fokus stehen Systeme, die über das Internet erreichbar sind und die zu groß sind, als dass sie von einem einzelnen kleinen Team betreut werden können.
Dafür stellt das Modul {curriculum-name} Techniken zur *Modularisierung* vor, die es erlauben, dass Änderungen in Bausteine des Systems gemacht werden können, ohne die anderen Bausteine zu beinflussen.
Unter Umständen führt die Modularisierung dazu, dass das System in mehrere Services aufgeteilt wird - sogenannte *Microservices*.  
Diese erlauben unabhängige Änderungen, erfordern aber Techniken zur Entwicklung und zum Betrieb verteilter Systeme, die dieses Modul ebenfalls behandelt.

Teilnehmer:innen können aufgrund fachlicher Anforderungen eine sinnvolle Modularisierungs-Strategie auswählen.
Sie kennen die Tradeoffs unterschiedlicher Strategien und können entscheiden, ob Microservices und Self-contained Systems zum Einsatz kommen sollen.
Sie können solche Systeme entwerfen und dafür sorgen, dass sie zuverlässig betrieben werden können.

// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

The {curriculum-short} module shows how architects can design software systems to make them easy to change and to extend.
The focus is on Internet-facing systems that are too large to be managed by a single small team.
To that end, the {curriculum-short} module presents techniques for *modularization* that allow changing building blocks of the system without affecting other building blocks.
Occasionally, modularization will lead to the system being split into multiple services - so-called *microservices*.
These allow independent changes but require techniques for developing and operating distributed systems.

Participants can use business requirements to choose a sensible modularization strategy.
They know the tradeoffs of various strategies and can decide whether to use microservices and self-contained systems.
They can design such systems and create the conditions for reliable operation.

// end::EN[]

