// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Das Modul {curriculum-name} zeigt, wie man mit modernen
Architektur-Ansätzen besonders flexible Systeme umsetzen kann.

Am Ende des Moduls kennen die Teilnehmerinnen und Teilnehmer Grundlagen von Microservices und Self-contained Systems und können Systeme auf Basis dieser Architektur-Konzepte entwerfen. Dabei können sie auch eine sinnvolle fachliche Aufteilung wie auch Konzepte für Continuous Delivery und Betrieb dieser Systeme erstellen.

// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

The module shows {curriculum-short} the participants how modern
architecture approaches can be used to build very flexible systems.

At the end of the module, the participants know the foundations of
microservices and self-contained systems. They are able to to design
systems based on these architecture concepts. They can come up with a
sensible split of the business logic as well as concepts for
continuous delivery and operations of these systems.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Hier bitte das Modul bzw. dessen Lerninhalte zusammenfassend in 5-8 Sätzen beschreiben. Dabei `{curriculum-name}`
nicht entfernen, beim Zusammenbauen wird dieser Platzhalter mit dem Modulnamen ersetzt.
====
// end::REMARK[]
